export const GET_BUDGETS = "GET_BUDGETS";
export const ADD_BUDGET = "ADD_BUDGET";
export const DELETE_BUDGET = "DELETE_BUDGET";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_BUDGET = "UPDATE_BUDGET";
export const CLEAR_BUDGETS  = "CLEAR_BUDGETS";
export const SET_LOADING = "SET_LOADING";
export const BUDGETS_ERROR = "BUDGETS_ERROR";

export const SEARCH_BUDGETS = "SEARCH_BUDGETS";

export const GET_EXPENSES = "GET_EXPENSES";
export const SET_CURRENT_EXPENSE = "SET_CURRENT_EXPENSE";
export const CLEAR_CURRENT_EXPENSE = "CLEAR_CURRENT_EXPENSE";
export const ADD_EXPENSE = "ADD_EXPENSES";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSES";
export const EXPENSES_ERROR = "EXPENSES_ERROR";