// Guest Types
export const GET_BUDGETS = "GET_BUDGETS";
export const ADD_BUDGET = "ADD_BUDGET";
export const DELETE_BUDGET = "DELETE_BUDGET";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_BUDGET = "UPDATE_BUDGET";
export const CLEAR_BUDGETS = "CLEAR_BUDGETS";
export const SET_LOADING = "SET_LOADING";
export const BUDGETS_ERROR = "BUDGETS_ERROR";

export const BUDGET_ID = "BUDGET_ID";
export const BUDGET_TITLE = "BUDGET_TITLE";
export const CURRENCY = "CURRENCY";
export const BUDGET_AMOUNT = "BUDGET_AMOUNT";
export const BALANCE = "BALANCE";
export const DATE_UPDATED = "DATE_UPDATED";
export const DATE_CREATED = "DATE_CREATED";
export const CLEAR_BUDGET = "CLEAR_BUDGET";
export const SET_MODIFY_BUDGET = "SET_MODIFY_BUDGET";
export const ADD_TO_BUDGET = "ADD_TO_BUDGET";
export const SUBTRACT_FROM_BUDGET = "SUBTRACT_FROM_BUDGET";

export const SET_GUEST_BUDGET = "SET_GUEST_BUDGET";
export const SET_GUEST_BUDGET_AND_SUB_BUDGET =
  "SET_GUEST_BUDGET_AND_SUB_BUDGET";
export const CLEAR_GUEST_BUDGET = "CLEAR_GUEST_BUDGET";

export const CLEAR_FILTER = "CLEAR_FILTER";

export const EXPENSES = "EXPENSES";
export const EXPENSE = "EXPENSE";
export const EXP_ID = "EXP_ID";
export const EXPENSE_NAME = "EXPENSE_NAME";
export const EXPENSE_AMOUNT = "EXPENSE_AMOUNT";
export const EXPENSE_DATE = "EXPENSE_DATE";

export const ADD_EXPENSE = "ADD_EXPENSES";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSES";
export const EXPENSES_ERROR = "EXPENSES_ERROR";
export const GET_EXPENSES = "GET_EXPENSES";
export const SET_CURRENT_EXPENSE = "SET_CURRENT_EXPENSE";
export const CLEAR_CURRENT_EXPENSE = "CLEAR_CURRENT_EXPENSE";

// User Types
export const USER_GET_BUDGETS = "USER_GET_BUDGETS";
export const USER_ADD_BUDGET = "USER_ADD_BUDGET";
export const USER_DELETE_BUDGET = "USER_DELETE_BUDGET";
export const USER_SET_CURRENT = "USER_SET_CURRENT";
export const USER_CLEAR_CURRENT = "USER_CLEAR_CURRENT";
export const USER_UPDATE_BUDGET = "USER_UPDATE_BUDGET";
export const USER_CLEAR_BUDGETS = "USER_CLEAR_BUDGETS";
export const USER_SET_LOADING = "USER_SET_LOADING";
export const USER_BUDGETS_ERROR = "USER_BUDGETS_ERROR";

export const USER_BUDGET_TITLE = "USER_BUDGET_TITLE";
export const USER_BUDGET_ID = "USER_BUDGET_ID";
export const USER_CURRENCY = "USER_CURRENCY";
export const USER_BUDGET_AMOUNT = "USER_BUDGET_AMOUNT";
export const USER_BALANCE = "USER_BALANCE";
export const USER_DATE_UPDATED = "USER_DATE_UPDATED";
export const USER_DATE_CREATED = "USER_DATE_CREATED";
export const USER_CLEAR_BUDGET = "USER_CLEAR_BUDGET";
export const USER_SET_MODIFY_BUDGET = "USER_SET_MODIFY_BUDGET";
export const USER_ADD_TO_BUDGET = "USER_ADD_TO_BUDGET";
export const USER_SUBTRACT_FROM_BUDGET = "USER_SUBTRACT_FROM_BUDGET";

export const SET_USER_BUDGET = "SET_USER_BUDGET";
export const SET_USER_BUDGET_AND_SUB_BUDGET = "SET_USER_BUDGET_AND_SUB_BUDGET";
export const USER_CLEAR_GUEST_BUDGET = "USER_CLEAR_GUEST_BUDGET";

export const USER_CLEAR_FILTER = "USER_CLEAR_FILTER";

export const USER_EXPENSES = "USER_EXPENSES";
export const USER_EXPENSE = "USER_EXPENSE";
export const USER_EXP_ID = "USER_EXP_ID";
export const USER_EXPENSE_NAME = "USER_EXPENSE_NAME";
export const USER_EXPENSE_AMOUNT = "USER_EXPENSE_AMOUNT";
export const USER_EXPENSE_DATE = "USER_EXPENSE_DATE";

export const USER_ADD_EXPENSE = "USER_ADD_EXPENSES";
export const USER_UPDATE_EXPENSE = "USER_UPDATE_EXPENSE";
export const USER_DELETE_EXPENSE = "USER_DELETE_EXPENSES";
export const USER_EXPENSES_ERROR = "USER_EXPENSES_ERROR";

export const USER_GET_EXPENSES = "USER_GET_EXPENSES";
export const USER_SET_CURRENT_EXPENSE = "USER_SET_CURRENT_EXPENSE";
export const USER_CLEAR_CURRENT_EXPENSE = "USER_CLEAR_CURRENT_EXPENSE";

export const SEARCH_BUDGETS = "SEARCH_BUDGETS";
export const USER_SEARCH_BUDGETS = "USER_SEARCH_BUDGETS";

// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
